<?php


namespace api\modules\web\forms;


use common\models\pay\WireTransfer;

class WireTransferForm extends WireTransfer
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['order_id', 'account', 'payment_voucher'], 'required'],
            [['order_id'], 'integer'],
            [['account'], 'string', 'max' => 50],
            ['account', 'validateAccount'],
            [['payment_voucher'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'order_id' => '订单ID',
            'account' => '收款账号',
            'payment_serial_number' => '付款流水号(客户)',
            'payment_voucher' => '付款凭证图片(客户)',
        ];
    }

    public function validateAccount($attribute)
    {
        if (!$this->hasErrors()) {
            $this->addError($attribute, '验证错误');
        }
    }

//    public function afterValidate()
//    {
//        return parent::beforeValidate(); // TODO: Change the autogenerated stub
//    }
}